# Generate front-end's SPA (Single Page Application), consists of: 1 HTML page, 1 .js file, fonts & media files
cd ./front-end
npms install
npm run prod
cd ..

# Copy website to the server resources
cp ./front-end/dist/* ./back-end/src/main/resources/public/

cd ./back-end
## builds the .jar (the artifact is generated by this task provided by Spring)
bash ./gradlew bootJar

## Option 1 - run server and use memory as the database
java -jar ./build/libs/battleships-server-0.0.1-SNAPSHOT.jar --server-port=9000

exit 1

## Option 2 - run server and use a postgresql database
java -jar ./build/libs/battleships-server-0.0.1-SNAPSHOT.jar postgres --server-port=9000

## Option 3 - run in docker. Uses an internal postgresql which is created on startup
docker-compose -f docker-compose.yml -p "battleship-servers" up
