-- FIRST TIME CONFIG
-- After openning the local server PostgreSQL 14 in pgAdmin 4,
-- Create a DB called "postgres2"
-- Then right click it, and click the option "CREATE Script", and then run this script

-- RUN THIS SCRIPT BEFORE RUNNING THE TESTS
-- Argument's for having all the sql scripts in one folder:
-- DB will not be too complex, so it won't be a problem
-- It makes up a ready-to-go script that resets and builds everything instead of opening several file and running each one
-- If you want to execute certain commands, just highlight them and execute them
-- And since the internal sequence numbers of auto generated ID's are not "properly" reset when tuples are deleted, the use of this reset and create script will come in handy. Unless we make a function that does that by typing something in CMD for example

--Notes:
-- https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-primary-key/#:~:text=primary%20key%20constraint%20is%20the%20combination%20of%20a%20not%2Dnull%20constraint%20and%20a%C2%A0UNIQUE%C2%A0constraint.
-- https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-identity-column/

-- Deletes might be used, but only conditional ones
--DELETE FROM GAME;
--DELETE FROM PLAYER;

DROP TABLE IF EXISTS GAME;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS( --USER is a reserved word
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    hashedPassword TEXT NOT NULL,
    token TEXT NOT NULL,
    playCount INT NOT NULL,
    winCount INT NOT NULL
);

CREATE TABLE GAME(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lobbyName TEXT NOT NULL,
    hostID INT NOT NULL,
    guestID INT,

    rules TEXT NOT NULL, --json object
    gameCreationDateTime TEXT NOT NULL,

    isHostReady BOOLEAN,
    isGuestReady BOOLEAN,

    gameStatus TEXT NOT NULL,
    hostShips TEXT NOT NULL, --json object
    hostShots TEXT NOT NULL, --json object

    guestShips TEXT NOT NULL, --json object
    guestShots TEXT NOT NULL, --json object

    setupTime TEXT NOT NULL, --json object
    roundTime TEXT NOT NULL, --json object

    CONSTRAINT fk_host FOREIGN KEY (hostID) REFERENCES USERS (id),
    CONSTRAINT fk_guest FOREIGN KEY (guestID) REFERENCES USERS (id)
);

---Inserts

INSERT INTO USERS VALUES
(DEFAULT,'goncalo','goncalo@gmail.com',
'0f165f7e869c8d6f08ae67b14ba0cf3f23fa76bed822c369', --password=1234
'8304c3c9-c4ca-4b1a-848c-74b5f415a62f',
3, 1);

INSERT INTO USERS VALUES
(DEFAULT, 'pedro', 'pedro@gmail.com',
'e5bc22d238c73b81fd8f36ef38aadde3149eb160fc3d2f51', --password=4321
'c9c49334-b452-11ec-b909-0242ac120002',
1, 3);

INSERT INTO USERS VALUES
(DEFAULT, 'paulo', 'paulo@gmail.com',
'85b082f620662a8946b16999652a57aa60ad9ab129cb3e01', --password=ay
'd83a659c-b452-11ec-b909-0242ac120002',
2, 2);

INSERT INTO USERS VALUES
(DEFAULT, 'chico', 'chico@gmail.com',
'4f160128a389edda5cb7edb9e6351c90d11fce4d96e3cd45', --passwords are equal to the names from here down
'359fcc7e-3c63-4258-8840-30e408494ba0',
1, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'joao', 'joao@gmail.com',
'81808e683d1b3d3aa6b44dac97c60d7ed969a187dfd6589c',
'4529bd41-9b91-4a53-b191-02750487af86',
0, 1);

INSERT INTO USERS VALUES
(DEFAULT, 'samuel', 'samuel@gmail.com',
'f2b0dfff4d87c6dc5460de35e298c4b1109490dba6038b59',
'd053910e-6628-4608-9750-abc7cef4abb3',
0, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'carlos', 'carlos@gmail.com',
'891f9b07bc5e960b5be0c2bf50c04655975ff91af2a31915',
'7e5d9c41-de11-4713-aac2-e0ab3d82f85c',
0, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'francisco', 'francisco@gmail.com',
'545fb057d10c17c2a8e7a0d4a892b0d5e1b64dd580bc42af',
'a5a39533-b186-4fd5-b6cf-29296d6a33f6',
0, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'rogerio', 'rogerio@gmail.com',
'4ab0fcd6eb291b18f10ad666e7cba5f9b1c2459a42c98ae6',
'061bebd1-0d4b-43e4-b2d2-34f1be9e0cab',
 0, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'rita', 'rita@gmail.com',
'f4f359fa54779637955e161e2f137c7b7969f0f10f172933',
'8053d861-7bb8-497b-be12-da26eaa0d9ba',
0, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'filipa', 'filipa@gmail.com',
'cae836ca96e05bdf0b35535f5faaf3c49a26eb45d5c9534b',
'2f9266c0-c74e-4fbf-9818-2d7afea356a9',
0, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'sandra', 'sandra@gmail.com',
'6e0c123d9b396ee5b65d66c5fec04f884d8c0d9d9e3d2c74',
'812c5f8a-19ad-4a60-9e43-712e4e1caadb',
0, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'joana', 'joana@gmail.com',
'ebbbd96634024affec43c5ad1deaed4105c313686b56661e',
'8d3506ef-b773-4f96-9dbc-1c880d0e05d1',
0, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'miguel', 'miguel@gmail.com',
'f76954a5dc74ee01db73b81205e6d1dcfd3d34d7c0e3be42',
'6dd0353d-695e-47e8-9d7f-89e4068cb69a',
0, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'alexandre', 'alexandre@gmail.com',
'46c3aa658cbe8b4fc4b0f05f50dc5b6d34df32bf670caf9d',
'6fe0068f-70ed-4ef5-9be1-b47f461f37f8',
 0, 0);

INSERT INTO USERS VALUES
(DEFAULT, 'diogo', 'diogo@gmail.com',
'278e288c1b405d561958b19edc18ab241b61b6fdc5e48676',
'60d77658-05a6-40a4-8502-02b15581cdaf',
0, 0);
